[package]
name = "cc-taskboard-server"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = { version = "0.14", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-postgres = { version = "0.7.5", features = ["runtime", "with-uuid-0_8", "with-serde_json-1"] }
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "0.8"
passwords = { version = "*", features = ["crypto"] }
rust-crypto = "^0.2"
